# Enable 256 colors and 24 bits
set -g default-terminal "tmux-256color"
set -as terminal-features ",rxvt*:RGB"

# Enable mouse support to select pane and scroll
set-window-option -g mouse on

# Keep a slightly larger backlog
set -g history-limit 30000

# Allow full command line used as title
set -g allow-set-title on

if-shell "id -n -G | grep -q production" \
    "source-file /etc/tmux.conf.production" \
    "source-file /etc/tmux.conf.regular"
